apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-octo
  labels:
    app: octo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: octo
        image: trentmohay/octo:mynewtag
